### ISSUE TITLE
Autocompletes for arguments with the same name for different commands are overridden

### ISSUE THREAD

**Issue by rm-you** [S3nS3IW00/JCommands#22]
I have a slashcommand with two subcommands: `subscribe` and `unsubscribe`. Both have an identically named argument.

The first one to load has this code:
```
        StringArgument<String> targetNameArgument = new StringArgument<>(
                "name", "The name of the target", String.class);
        SearchAutocomplete searchAutocomplete = new SearchAutocomplete(
                SearchAutocomplete.SearchType.CONTAINS, targetStringList
        ).ignoreCase().limit(10).sort(SearchAutocomplete.SortType.ASCENDING).minCharToSearch(2);
        targetNameArgument.addAutocomplete(searchAutocomplete);
        addArgument(targetNameArgument);
```

The second has this code:
```
        StringArgument<String> targetNameArgument = new StringArgument<>(
                "name", "The name of the target", String.class);
        Autocomplete autocomplete = new Autocomplete(subscriptions);
        targetNameArgument.addAutocomplete(autocomplete);
        addArgument(targetNameArgument);
```

When the bot runs, BOTH commands' `name` arg has the autocomplete from the second command. If I comment out the autocomplete for the second command, the first command's autocomplete works correctly. If I rename the argument to be unique, both work correctly. Is it somehow storing them by name globally and overwriting the original one even though it is on a different command?

**Comment by S3nS3IW00** [comment]
Hi! Sorry for the late response.

Thanks for your report, I can confirm that this is a real issue with autocompletes. The problem is the same name, because options do not have an id on discord therefore jcommands uses the name to identify the argument. I will fix it asap, until then renaming one of the arguments could be a solution.

**Comment by rm-you** [comment]
Thanks for responding, and no worries! Yes, for now I've renamed one argument, but it is awkward because the commands are related so it is a strange UX to have essentially the same option use a different name in another command. However, no rush on this, as I've had to backburner this work for now for other reasons. 😅
Just hoping you can fix it eventually for the sake of others -- or they can find this issue and be less confused than I was when this happened to me. 😂

**Comment by S3nS3IW00** [comment]
I made a `7.1.0-SNAPSHOT` version that contains the fix, you can check if it solves the issue.

**Comment by rm-you** [comment]
Thanks! Unfortunately I don't have an easy way to test this anymore, but this is a good fix for posterity. 👌
